/**
 * Chat UI themes for Monica.
 * Each theme maps to CSS custom properties on `.chats-page[data-theme]`.
 */

export const THEME_STORAGE_KEY = 'monica_chat_theme';

/** @typedef {{
 *  id: string,
 *  name: string,
 *  tag: string,
 *  description: string,
 *  preview: { bg: string, surface: string, accent: string, bubble: string, text: string },
 *  vars: Record<string, string>,
 * }} ChatTheme */

/** @type {ChatTheme[]} */
export const CHAT_THEMES = [
  {
    id: 'monica',
    name: 'Monica',
    tag: 'По умолчанию',
    description: 'Спокойный графит с приглушённым акцентом — базовый вид мессенджера.',
    preview: {
      bg: '#141417',
      surface: '#1c1c21',
      accent: '#6e6a8a',
      bubble: '#2f6fed',
      text: '#ececf0',
    },
    vars: {
      '--bg-primary': '#141417',
      '--bg-secondary': '#17171b',
      '--bg-tertiary': '#1b1b20',
      '--page-bg': '#151518',
      '--surface-primary': '#18181c',
      '--surface-secondary': '#1c1c21',
      '--surface-elevated': '#222228',
      '--border-subtle': 'rgba(160, 160, 175, 0.1)',
      '--border-default': 'rgba(160, 160, 175, 0.16)',
      '--border-hover': 'rgba(160, 160, 175, 0.26)',
      '--border-active': 'rgba(120, 110, 150, 0.55)',
      '--text-primary': '#ececf0',
      '--text-secondary': '#a8a8b3',
      '--text-muted': '#787884',
      '--accent-primary': '#6e6a8a',
      '--accent-strong': '#5f5a7d',
      '--accent-violet': '#6d6688',
      '--bubble-own': '#2f6fed',
      '--bubble-own-text': '#f4f7ff',
      '--bubble-other': '#222228',
      '--radius-sm': '8px',
      '--radius-md': '10px',
      '--radius-lg': '12px',
      '--radius-xl': '16px',
      '--theme-font': "Inter, Manrope, 'Segoe UI', system-ui, sans-serif",
      '--theme-blur': '14px',
      '--theme-surface-alpha': '1',
    },
  },
  {
    id: 'glass',
    name: 'Glass',
    tag: 'Гласморфизм',
    description: 'Матовые стеклянные панели, мягкий blur и холодный голубой акцент.',
    preview: {
      bg: '#0c1424',
      surface: 'rgba(40, 60, 96, 0.55)',
      accent: '#7eb6ff',
      bubble: '#3d7cff',
      text: '#eaf2ff',
    },
    vars: {
      '--bg-primary': '#0b1220',
      '--bg-secondary': '#101a2e',
      '--bg-tertiary': '#15233a',
      '--page-bg': 'linear-gradient(165deg, #0a1222 0%, #152848 48%, #0d182c 100%)',
      '--surface-primary': 'rgba(22, 34, 56, 0.72)',
      '--surface-secondary': 'rgba(28, 44, 72, 0.78)',
      '--surface-elevated': 'rgba(40, 58, 92, 0.82)',
      '--border-subtle': 'rgba(170, 200, 255, 0.1)',
      '--border-default': 'rgba(170, 200, 255, 0.18)',
      '--border-hover': 'rgba(170, 200, 255, 0.3)',
      '--border-active': 'rgba(126, 182, 255, 0.55)',
      '--text-primary': '#eaf2ff',
      '--text-secondary': '#a8c0e0',
      '--text-muted': '#7a93b5',
      '--accent-primary': '#7eb6ff',
      '--accent-strong': '#5a9cff',
      '--accent-violet': '#8aa4ff',
      '--bubble-own': '#3d7cff',
      '--bubble-own-text': '#f5f9ff',
      '--bubble-other': 'rgba(30, 46, 74, 0.9)',
      '--radius-sm': '10px',
      '--radius-md': '14px',
      '--radius-lg': '18px',
      '--radius-xl': '22px',
      '--theme-font': "Manrope, Inter, 'Segoe UI', system-ui, sans-serif",
      '--theme-blur': '22px',
      '--theme-surface-alpha': '0.78',
    },
  },
  {
    id: 'sketch',
    name: 'Sketch',
    tag: 'Скетч',
    description: 'Светлая «бумага», чернильный текст и слегка неровные края, как в блокноте.',
    preview: {
      bg: '#f3efe6',
      surface: '#fffdf8',
      accent: '#2a2a2a',
      bubble: '#e8e0d0',
      text: '#1c1c1c',
    },
    vars: {
      '--bg-primary': '#efe9dc',
      '--bg-secondary': '#f6f1e7',
      '--bg-tertiary': '#ebe4d6',
      '--page-bg': '#f3efe6',
      '--surface-primary': '#fffdf8',
      '--surface-secondary': '#fffaf0',
      '--surface-elevated': '#fffdf8',
      '--border-subtle': 'rgba(40, 36, 28, 0.12)',
      '--border-default': 'rgba(40, 36, 28, 0.28)',
      '--border-hover': 'rgba(40, 36, 28, 0.42)',
      '--border-active': 'rgba(40, 36, 28, 0.65)',
      '--text-primary': '#1c1c1c',
      '--text-secondary': '#4a463e',
      '--text-muted': '#7a7468',
      '--accent-primary': '#2a2a2a',
      '--accent-strong': '#111111',
      '--accent-violet': '#3d3a34',
      '--bubble-own': '#d9d0bc',
      '--bubble-own-text': '#1a1814',
      '--bubble-other': '#fffdf8',
      '--radius-sm': '4px',
      '--radius-md': '6px',
      '--radius-lg': '8px',
      '--radius-xl': '10px',
      '--theme-font': "Georgia, 'Times New Roman', 'Palatino Linotype', serif",
      '--theme-blur': '0px',
      '--theme-surface-alpha': '1',
    },
  },
  {
    id: 'ibm',
    name: 'IBM 3270',
    tag: 'Терминал',
    description: 'Зелёный фосфор на чёрном — эстетика старых терминалов IBM.',
    preview: {
      bg: '#010805',
      surface: '#03140c',
      accent: '#33ff66',
      bubble: '#0a2a14',
      text: '#33ff66',
    },
    vars: {
      '--bg-primary': '#010805',
      '--bg-secondary': '#02100a',
      '--bg-tertiary': '#04180e',
      '--page-bg': '#000804',
      '--surface-primary': '#03140c',
      '--surface-secondary': '#052016',
      '--surface-elevated': '#07301f',
      '--border-subtle': 'rgba(51, 255, 102, 0.12)',
      '--border-default': 'rgba(51, 255, 102, 0.28)',
      '--border-hover': 'rgba(51, 255, 102, 0.45)',
      '--border-active': 'rgba(51, 255, 102, 0.7)',
      '--text-primary': '#33ff66',
      '--text-secondary': '#22c24e',
      '--text-muted': '#178a38',
      '--accent-primary': '#33ff66',
      '--accent-strong': '#1fd95a',
      '--accent-violet': '#66ff99',
      '--bubble-own': '#0a2a14',
      '--bubble-own-text': '#66ff99',
      '--bubble-other': '#031a0e',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--theme-font': "'IBM Plex Mono', 'Consolas', 'Courier New', monospace",
      '--theme-blur': '0px',
      '--theme-surface-alpha': '1',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    tag: 'Арктика',
    description: 'Холодная палитра: полярные синие и серые, спокойный контраст.',
    preview: {
      bg: '#2e3440',
      surface: '#3b4252',
      accent: '#88c0d0',
      bubble: '#5e81ac',
      text: '#eceff4',
    },
    vars: {
      '--bg-primary': '#2e3440',
      '--bg-secondary': '#3b4252',
      '--bg-tertiary': '#434c5e',
      '--page-bg': '#2e3440',
      '--surface-primary': '#3b4252',
      '--surface-secondary': '#434c5e',
      '--surface-elevated': '#4c566a',
      '--border-subtle': 'rgba(216, 222, 233, 0.08)',
      '--border-default': 'rgba(216, 222, 233, 0.16)',
      '--border-hover': 'rgba(216, 222, 233, 0.28)',
      '--border-active': 'rgba(136, 192, 208, 0.55)',
      '--text-primary': '#eceff4',
      '--text-secondary': '#d8dee9',
      '--text-muted': '#a0a8b8',
      '--accent-primary': '#88c0d0',
      '--accent-strong': '#81a1c1',
      '--accent-violet': '#b48ead',
      '--bubble-own': '#5e81ac',
      '--bubble-own-text': '#eceff4',
      '--bubble-other': '#434c5e',
      '--radius-sm': '8px',
      '--radius-md': '10px',
      '--radius-lg': '12px',
      '--radius-xl': '16px',
      '--theme-font': "Inter, 'Segoe UI', system-ui, sans-serif",
      '--theme-blur': '12px',
      '--theme-surface-alpha': '1',
    },
  },
  {
    id: 'amber',
    name: 'Amber CRT',
    tag: 'Янтарный экран',
    description: 'Тёплый янтарный терминал — как мониторы 80-х.',
    preview: {
      bg: '#120c04',
      surface: '#1c1408',
      accent: '#ffb000',
      bubble: '#3a2808',
      text: '#ffc857',
    },
    vars: {
      '--bg-primary': '#120c04',
      '--bg-secondary': '#1a1206',
      '--bg-tertiary': '#24180a',
      '--page-bg': '#0e0902',
      '--surface-primary': '#1c1408',
      '--surface-secondary': '#261a0c',
      '--surface-elevated': '#322210',
      '--border-subtle': 'rgba(255, 176, 0, 0.1)',
      '--border-default': 'rgba(255, 176, 0, 0.22)',
      '--border-hover': 'rgba(255, 176, 0, 0.38)',
      '--border-active': 'rgba(255, 176, 0, 0.65)',
      '--text-primary': '#ffc857',
      '--text-secondary': '#d9a020',
      '--text-muted': '#9a7014',
      '--accent-primary': '#ffb000',
      '--accent-strong': '#e09800',
      '--accent-violet': '#ffcc66',
      '--bubble-own': '#3a2808',
      '--bubble-own-text': '#ffe099',
      '--bubble-other': '#221608',
      '--radius-sm': '2px',
      '--radius-md': '4px',
      '--radius-lg': '6px',
      '--radius-xl': '8px',
      '--theme-font': "'IBM Plex Mono', Consolas, monospace",
      '--theme-blur': '0px',
      '--theme-surface-alpha': '1',
    },
  },
  {
    id: 'noir',
    name: 'Noir',
    tag: 'Кино',
    description: 'Высокий контраст, уголь и золотая вспышка — как кадр из нуара.',
    preview: {
      bg: '#0a0a0a',
      surface: '#161616',
      accent: '#c9a227',
      bubble: '#2a2414',
      text: '#f2f2f2',
    },
    vars: {
      '--bg-primary': '#0a0a0a',
      '--bg-secondary': '#111111',
      '--bg-tertiary': '#1a1a1a',
      '--page-bg': '#050505',
      '--surface-primary': '#141414',
      '--surface-secondary': '#1c1c1c',
      '--surface-elevated': '#262626',
      '--border-subtle': 'rgba(255, 255, 255, 0.06)',
      '--border-default': 'rgba(201, 162, 39, 0.28)',
      '--border-hover': 'rgba(201, 162, 39, 0.45)',
      '--border-active': 'rgba(201, 162, 39, 0.7)',
      '--text-primary': '#f2f2f2',
      '--text-secondary': '#b8b8b8',
      '--text-muted': '#7a7a7a',
      '--accent-primary': '#c9a227',
      '--accent-strong': '#a8861c',
      '--accent-violet': '#d4b45a',
      '--bubble-own': '#2a2414',
      '--bubble-own-text': '#f7efd4',
      '--bubble-other': '#1a1a1a',
      '--radius-sm': '6px',
      '--radius-md': '8px',
      '--radius-lg': '10px',
      '--radius-xl': '12px',
      '--theme-font': "'Playfair Display', Georgia, serif",
      '--theme-blur': '10px',
      '--theme-surface-alpha': '1',
    },
  },
  {
    id: 'abyss',
    name: 'Abyss',
    tag: 'Океан',
    description: 'Глубокий изумруд и бирюза — погружение в тёмную воду.',
    preview: {
      bg: '#061416',
      surface: '#0d2428',
      accent: '#2dd4bf',
      bubble: '#0f766e',
      text: '#e6fffa',
    },
    vars: {
      '--bg-primary': '#061416',
      '--bg-secondary': '#0a1c20',
      '--bg-tertiary': '#0f282e',
      '--page-bg': 'linear-gradient(180deg, #041012 0%, #0a2228 55%, #06181c 100%)',
      '--surface-primary': '#0d2428',
      '--surface-secondary': '#123038',
      '--surface-elevated': '#184048',
      '--border-subtle': 'rgba(45, 212, 191, 0.08)',
      '--border-default': 'rgba(45, 212, 191, 0.18)',
      '--border-hover': 'rgba(45, 212, 191, 0.32)',
      '--border-active': 'rgba(45, 212, 191, 0.55)',
      '--text-primary': '#e6fffa',
      '--text-secondary': '#99f6e4',
      '--text-muted': '#5f9e96',
      '--accent-primary': '#2dd4bf',
      '--accent-strong': '#14b8a6',
      '--accent-violet': '#5eead4',
      '--bubble-own': '#0f766e',
      '--bubble-own-text': '#ecfeff',
      '--bubble-other': '#0f2a30',
      '--radius-sm': '10px',
      '--radius-md': '12px',
      '--radius-lg': '16px',
      '--radius-xl': '20px',
      '--theme-font': "Manrope, Inter, system-ui, sans-serif",
      '--theme-blur': '16px',
      '--theme-surface-alpha': '0.92',
    },
  },
  {
    id: 'copper',
    name: 'Copper',
    tag: 'Мастерская',
    description: 'Тёплая медь и уголь — индустриальная мастерская.',
    preview: {
      bg: '#1a120e',
      surface: '#2a1c16',
      accent: '#d08a4a',
      bubble: '#8b4e2a',
      text: '#f3e6d8',
    },
    vars: {
      '--bg-primary': '#1a120e',
      '--bg-secondary': '#221610',
      '--bg-tertiary': '#2c1c14',
      '--page-bg': '#16100c',
      '--surface-primary': '#2a1c16',
      '--surface-secondary': '#34241c',
      '--surface-elevated': '#403028',
      '--border-subtle': 'rgba(208, 138, 74, 0.1)',
      '--border-default': 'rgba(208, 138, 74, 0.22)',
      '--border-hover': 'rgba(208, 138, 74, 0.38)',
      '--border-active': 'rgba(208, 138, 74, 0.6)',
      '--text-primary': '#f3e6d8',
      '--text-secondary': '#d2b49a',
      '--text-muted': '#9a7a62',
      '--accent-primary': '#d08a4a',
      '--accent-strong': '#b87238',
      '--accent-violet': '#e0a46a',
      '--bubble-own': '#8b4e2a',
      '--bubble-own-text': '#fff4ea',
      '--bubble-other': '#2c1e18',
      '--radius-sm': '8px',
      '--radius-md': '10px',
      '--radius-lg': '12px',
      '--radius-xl': '14px',
      '--theme-font': "Inter, Manrope, system-ui, sans-serif",
      '--theme-blur': '10px',
      '--theme-surface-alpha': '1',
    },
  },
  {
    id: 'brutal',
    name: 'Brutal',
    tag: 'Брутализм',
    description: 'Жёсткие углы, жёлтый сигнал на чёрном — без скруглений и теней.',
    preview: {
      bg: '#000000',
      surface: '#111111',
      accent: '#ffe600',
      bubble: '#ffe600',
      text: '#ffffff',
    },
    vars: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#0a0a0a',
      '--bg-tertiary': '#141414',
      '--page-bg': '#000000',
      '--surface-primary': '#111111',
      '--surface-secondary': '#1a1a1a',
      '--surface-elevated': '#242424',
      '--border-subtle': 'rgba(255, 230, 0, 0.14)',
      '--border-default': 'rgba(255, 230, 0, 0.35)',
      '--border-hover': 'rgba(255, 230, 0, 0.55)',
      '--border-active': '#ffe600',
      '--text-primary': '#ffffff',
      '--text-secondary': '#d0d0d0',
      '--text-muted': '#888888',
      '--accent-primary': '#ffe600',
      '--accent-strong': '#e6cf00',
      '--accent-violet': '#fff04d',
      '--bubble-own': '#ffe600',
      '--bubble-own-text': '#000000',
      '--bubble-other': '#1a1a1a',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--theme-font': "'Arial Black', Impact, Haettenschweiler, sans-serif",
      '--theme-blur': '0px',
      '--theme-surface-alpha': '1',
    },
  },
];

export const DEFAULT_THEME_ID = 'monica';

export function getThemeById(id) {
  return CHAT_THEMES.find((theme) => theme.id === id) || CHAT_THEMES[0];
}

export function readStoredThemeId() {
  try {
    const raw = localStorage.getItem(THEME_STORAGE_KEY);
    if (raw && CHAT_THEMES.some((theme) => theme.id === raw)) return raw;
  } catch {
    /* ignore */
  }
  return DEFAULT_THEME_ID;
}

export function storeThemeId(id) {
  try {
    localStorage.setItem(THEME_STORAGE_KEY, id);
  } catch {
    /* ignore */
  }
}
